opt_in_rules:
  - anyobject_protocol
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - expiring_todo
  - file_name
  - file_header
  - first_where
  - last_where
  - legacy_random
  - let_var_whitespace
  - modifier_order
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unused_declaration
  - unused_import
  - redundant_nil_coalescing
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - yoda_condition

disabled_rules:
  - cyclomatic_complexity

line_length:
  warning: 120
  error: 120

overridden_super_call:
  severity: error

private_action:
  severity: error

private_outlet:
  severity: error

prohibited_super_call:
  severity: error

sorted_imports:
  severity: error

type_body_length:
  - 300
  - 400
