name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: "🧹 Lint"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 🧹 Lint
      uses: norio-nomura/action-swiftlint@3.2.1
  
  test:
    name: "🧪 Test"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: 👷 Build
      run: swift build -v
    - name: 🧪 Run tests
      run: swift test -v
